export type ActionType =
  | 'navigate'
  | 'wait-click'
  | 'click'
  | 'fill'
  | 'type'
  | 'end'
  | 'clear'
  | 'wait-visible'
  | 'wait-hidden'
  | 'click-wait-response'
  | 'enter'
  | 'reload'
  | 'select'
  | 'drag-and-drop';
